spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist
    username: user1
    password: 1qaz2wsx
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
      #data-locations: classpath:demo_data.sql
  liquibase:
    changelog: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: 0YHQtdC60YDQtdGC0L3Ri9C50LrQvtC00LrQvtGC0L7RgNGL0LnQvdC40LrRgtC+0L3QtdC30L3QsNC10YI=
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-responce: false
