spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist
    username: user1
    password: 1qaz2wsx
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: 0YHQtdC60YDQtdGC0L3Ri9C50LrQvtC00LrQvtGC0L7RgNGL0LnQvdC40LrRgtC+0L3QtdC30L3QsNC10YI=
    access: 3600000
    refresh: 2592000000